services:
  runner:
    image: data.forgejo.org/forgejo/runner:11
    container_name: runner
    # User without root privileges, but with access to `./data`.
    #user: 1001:1001
    user: root:root
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    # sleep
    #command: '/bin/sh -c "while : ; do sleep 1 ; done ;"'
    # daemon
    command: /bin/sh -c "sleep 5; forgejo-runner daemon --config /data/config.yml"
    networks:
      - runner-net
      - default

networks:
  runner-net:
    driver: bridge
    name: runner-netriver: bridge
    name: runner-net
