---
- name: idempotent docker services deployment
  hosts: all
  become: true

  vars_files:
    - secret.yml

  vars:
    services_path: "/home/dockeruser/services"

    apps:
      - authelia
      - forgejo
      - immich
      - vaultwarden
      - npm
      - monitoring
      - dockge
      - filebrowser
      - homepage
      - matrix
      - pihole
      - syncthing
      - zerobyte

  tasks:
    - name: be sure that application directories exist
      ansible.builtin.file:
        path: "{{ services_path }}/{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ apps }}"

    - name: copy docker compose conf
      ansible.builtin.template:
        src: "{{ item }}/docker-compose.yml" 
        dest: "{{ services_path }}/{{ item }}/docker-compose.yml"
        mode: '0644'
      loop: "{{ apps }}"
      register: compose_templates

    - name: apply docker compose and start services
      community.docker.docker_compose_v2:
        project_src: "{{ services_path }}/{{ item }}"
        state: present
        docker_host: unix:///var/run/docker.sock
      loop: "{{ apps }}"
