name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: docker
    container:
      image: node:20-alpine
      env:
        DOCKER_HOST: tcp://docker-in-docker:2375
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: apk add --no-cache ansible docker-cli
      - name: Run Ansible
        run: ansible-playbook deploy.yml -i "localhost," --connection=local
