name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: docker
    container:
      image: node:20-alpine
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: apk add --no-cache ansible docker-cli docker-cli-compose
      - name: run Ansible
        run: ansible-playbook deploy.yml -i "localhost," --connection=local
