services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /home/dockeruser/services:/home/dockeruser/services
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/home/dockeruser/services
networks:
  proxy_net:
    external: true
